apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::367101852765:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-112CPVTMS95J
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::367101852765:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-22T04:19:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "802"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: fa381a89-034e-4b9d-8584-ab7a443e61f6
